### PR TITLE
feat: add IPermit2 interface

### PR DESCRIPTION
**Pull request by PaulRBerg**
Addresses #213.

### CODE REVIEW

**Comment by ewilz** [comment]
@marktoda do you have any opinions on this?? I think we had left the these two separate interfaces intentionally.

This issue alludes to frozen version issue, but I don't see how that's related as that is the impl contracts (not the interface contracts which are relevant to this PR)

**Comment by ewilz** [comment]
ok going to merge this still

**Comment by PaulRBerg** [comment]
> This issue alludes to frozen version issue, but I don't see how that's related as that is the impl contracts

Without an interface like the one introduced by this PR, users who want to use the signature and the allowance modes at the same time have to use the `Permit2` contract itself; but they can only do so only if they are on Solidity `0.8.17`.

**Comment by PaulRBerg** [comment]
Thanks for merging!

**Comment by ewilz** [comment]
we've just been importing both interfaces as needed

**Comment by PaulRBerg** [comment]
Yeah but you can't use them in all cases, e.g. struct fields. It's either this:

```solidity
struct Permit2Thingy {
    IAllowanceTransfer permit2Address;
```

Or this:

```solidity
struct Permit2Thingy {
    ISignatureTransfer permit2Address;
```

**Pull request merged**
