### PR TITLE
refactor: use relative path that stays inside folder

### PR DESCRIPTION
**Pull request by fubuloubu**
Currently this path extends outside the root contract folder path, which could cause issues with tools that expect to use this tools from within the `src` path

### CODE REVIEW

**Review by marktoda — APPROVED** [review]

**Comment by marktoda** [comment]
oh good call, ty

**Review by marktoda — APPROVED** [review]

**Comment by Issalk** [comment]
> Currently this path extends outside the root contract folder path, which could cause issues with tools that expect to use this tools from within the `src` path

**Review by Issalk — COMMENTED** [review]
Issa

**Comment by Issalk** [comment]
> oh good call, ty

**Pull request merged**
