### PR TITLE
feat: add deploy permit2 util

### PR DESCRIPTION
**Pull request by marktoda**
For folks building on top of permit2 it's kinda annoying to have to use viaIR just becuase permit2 uses viaIR. This commit adds a test utility that they can import to deploy permit2 from precompiled bytecode to avoid needing to recompile it on their end

### CODE REVIEW

**Review by snreynolds — COMMENTED** [review]
this is sweet. Maybe we could add this feature to the README? Like import DeployPermit2.sol and use `permit2 = new Permit2(deployPermit2())`

**Review by snreynolds — APPROVED** [review]

**Comment by PaulRBerg** [comment]
Actually, the issue is not just that integrating repos have to use via IR. It's also a matter of accuracy - I would much rather have our tests run against the genuine Permit2 bytecode, rather than a version compiled with our Solidity settings (which are very likely different from yours).

I am glad that you have added this deploy utility!

**Comment by PaulRBerg** [comment]
> Like `import DeployPermit2.sol `and use `permit2 = new Permit2(deployPermit2())`

Yes, but that would be more like this:

```solidity
new DeployPermit2().deployPermit2();
```

By the way - why hasn't the function been named [`run`](https://book.getfoundry.sh/tutorials/best-practices#scripts)? It looks a bit repetitive.

**Comment by PaulRBerg** [comment]
Also: consider adding explicit `public` visibility for the `PERMIT2_ADDRESS` constant, since it is not clear whether you have intentionally made it public.

**Comment by sebastiantf** [comment]
Why does the bytecode differ from the one in this repo and the one used in UniswapX? I tried using the one in this repo and was getting mismatching signature. But trying the one on UniswapX works fine.

There is a diff bw the two bytecodes

**Pull request merged**
